<?php


use Phinx\Seed\AbstractSeed;

class MenuSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run(): void
    {
        $result = $this->query("TRUNCATE TABLE menu");
        $result = $this->query("TRUNCATE TABLE crm_pages");

        $this->menu();
        $this->crmPages();


    }

    private function menu(){
        $sql = "insert into menu (menu_id, menu_name, icon_class, sort_index, active, icon_class_new)
                values  (1, 'Properties', 'icon-prop', 5, 1, 'font-icon font-icon-build'),
                        (2, 'Customer Service', 'icon-jobs', 2, 1, 'fa fa-wrench'),
                        (3, 'Data Specialists', 'icon-daily-items', 3, 1, 'glyphicon glyphicon-time'),
                        (4, 'Reports', 'icon-reports', 6, 1, 'fa fa-pie-chart'),
                        (5, 'Technicians', 'icon-tech', 7, 1, 'fa fa-user-secret'),
                        (6, 'Agencies', 'icon-agencies', 8, 1, 'fa fa-building-o'),
                        (7, 'Calendar', 'icon-calendar', 9, 1, 'font-icon font-icon-calend'),
                        (8, 'Users', 'icon-users', 10, 1, 'fa fa-users'),
                        (9, 'Sales', 'icon-sales', 11, 1, 'fa fa-briefcase'),
                        (10, 'Forms', 'icon-admin', 12, 1, 'fa fa-file-text'),
                        (11, 'Admin', 'icon-admin', 13, 1, 'fa fa-user'),
                        (12, 'Messages', 'icon-message', 14, 1, 'font-icon font-icon-comments'),
                        (13, 'Vehicles/Tools', 'icon-vehicle', 15, 1, 'fa fa-car'),
                        (14, 'Accounts', 'icon-reports', 16, 1, 'fa fa-file-text'),
                        (15, 'SMS', 'icon-message', 17, 1, 'fa fa-mobile'),
                        (16, 'OPS Daily Items', 'icon-daily-items', 4, 0, 'glyphicon glyphicon-time'),
                        (17, 'Scheduling', 'icon-reports', 1, 1, 'glyphicon glyphicon-road'),
                        (18, 'API', 'icon-reports', 4, 1, 'fa fa-bar-chart'),
                        (19, 'Create a Support Ticket', null, null, 0, ''),
                        (20, 'Contact IT', 'icon-peoples', 18, 1, 'fa fa-desktop'),
                        (21, 'Feedback', 'icon-admin', 19, 1, 'glyphicon glyphicon-thumbs-down');";
        return $this->query($sql);
    }

    private function crmPages(){
        $sql = "insert into crm_pages (crm_page_id, page_name, page_url, menu, active)
                    values  (1, 'Active Job Properties', 'active_properties.php', 1, 0),
                            (2, 'Active Properties', '/properties/active_properties', 1, 1),
                            (3, 'Add Private Residential', 'add_private_residential.php', 1, 0),
                            (4, 'Add Properties', 'add_property_static.php', 1, 1),
                            (5, 'Import Properties', 'import_properties.php', 1, 0),
                            (6, 'Inactive Properties', 'view_deleted_properties.php', 1, 0),
                            (7, 'After Hours Jobs', 'outside_tech_hours.php', 17, 1),
                            (8, 'Allocate', 'allocate.php', 17, 1),
                            (9, 'All Jobs', 'view_jobs.php', 2, 0),
                            (10, 'Booked Jobs', 'booked_jobs.php', 2, 0),
                            (11, 'Cancelled Jobs', 'cancelled_jobs.php', 2, 0),
                            (12, 'Completed Jobs', 'completed_jobs.php', 2, 0),
                            (13, 'New Lease', 'cot_jobs.php', 17, 0),
                            (14, 'Deleted Jobs', 'deleted_jobs.php', 2, 0),
                            (15, 'DHA', 'dha_jobs.php', 17, 1),
                            (16, 'Escalates', 'escalate.php', 2, 1),
                            (17, 'Merged Jobs', 'merged_jobs.php', 17, 1),
                            (18, 'Platform Invoicing ', 'platform_invoicing.php', 3, 1),
                            (19, 'On Hold Jobs', 'on_hold_jobs.php', 17, 1),
                            (20, 'Pre Completion', 'precompleted_jobs.php', 17, 1),
                            (21, 'New Jobs', 'send_letter_jobs.php', 3, 1),
                            (22, 'Service Due Jobs', 'service_due_jobs.php', 3, 1),
                            (23, 'Set Tech Run', 'set_tech_run.php', 17, 1),
                            (24, 'Todays Jobs', 'todays_jobs.php', 2, 0),
                            (25, 'To Be Booked', 'to_be_booked_jobs.php', 17, 1),
                            (26, 'To Be Invoiced', 'to_be_invoiced_jobs.php', 3, 1),
                            (27, 'Urgent Jobs', 'urgent_jobs.php', 17, 1),
                            (28, 'Vacant Jobs', 'vacant_jobs.php', 17, 1),
                            (29, 'Overdue 30+', 'ageing_jobs_30_to_60.php', 17, 1),
                            (30, 'Action Required', 'action_required_jobs.php', 2, 1),
                            (31, 'Agency Keys', 'agency_keys.php', 3, 0),
                            (32, 'Duplicate Postcode', 'duplicate_postcode.php', 3, 1),
                            (33, 'Duplicate Properties', 'duplicate_properties.php', 3, 1),
                            (35, 'Last Contact', 'last_contact.php', 2, 1),
                            (36, 'Missing Region Jobs', 'missing_region.php', 17, 1),
                            (37, 'Multiple Jobs', 'multiple_jobs.php', 3, 1),
                            (38, 'No Active Job Properties', 'no_active_job_properties.php', 3, 1),
                            (39, 'No ID Properties', 'no_id_properties.php', 3, 1),
                            (40, 'Unserviced Properties', 'unserviced.php', 3, 1),
                            (41, 'Admin Report', 'report_admin.php', 4, 0),
                            (42, 'Agency Keys', 'agency_keys.php', 4, 0),
                            (43, 'Booked Report', 'booked.php', 4, 0),
                            (44, 'Call Centre', 'call_centre_report.php', 4, 0),
                            (45, 'Completed Jobs', 'completed_report.php', 4, 0),
                            (46, 'Cron Report', 'cron_report.php', 4, 0),
                            (47, 'Daily Figures', 'daily_figures.php', 4, 0),
                            (48, 'Expiring Alarms', 'expiring.php', 4, 0),
                            (49, 'Figures', 'figures.php', 4, 0),
                            (50, 'Icons', 'icons.php', 4, 0),
                            (51, 'Installed Alarms', 'installed_alarms.php', 4, 0),
                            (52, 'Key Tracking Report', 'key_tracking.php', 4, 0),
                            (53, 'KPIs', 'kpi.php', 4, 1),
                            (54, 'Missed Jobs', 'missed_jobs.php', 4, 0),
                            (55, 'MM Agencies', 'maintenance_program_agencies.php', 4, 0),
                            (56, 'New Jobs Report', 'new_jobs_report.php', 4, 0),
                            (57, 'New Properties Report', 'new_properties_report.php', 4, 0),
                            (58, 'No Auto Renew Agencies', 'no_auto_renew_agencies.php', 4, 0),
                            (59, 'Region Numbers', 'region_numbers.php', 4, 0),
                            (60, 'Sales Report', 'report_sales_admin.php', 4, 0),
                            (61, 'Service Due Report', 'servicedue.php', 4, 0),
                            (62, 'Service Due (Next Month)', 'future_pendings.php', 4, 0),
                            (63, 'Status Report', 'status.php', 4, 0),
                            (64, 'Whiteboard', 'whiteboard.php', 4, 0),
                            (65, 'Add Purchase Order', 'add_purchase_order.php', 5, 1),
                            (66, 'Contractors', 'contractors.php', 5, 0),
                            (67, 'Overall Tech Schedule', 'view_overall_schedule.php', 5, 1),
                            (68, 'Purchase Orders', 'purchase_order.php', 5, 0),
                            (69, 'Stock Items', 'add_tech_stock.php', 5, 0),
                            (70, 'Tech Documents', 'resources/tech_doc_admin', 5, 1),
                            (71, 'Tech Stocktake', 'stock/update_tech_stock', 5, 1),
                            (72, 'Tech Stock Report', 'tech_stock.php', 5, 0),
                            (73, 'Tech View Documents', 'resources/index', 5, 1),
                            (74, 'View Technicians', 'view_techs.php', 5, 0),
                            (75, 'Add Agency', 'add_agency_static.php', 6, 1),
                            (76, 'Active Agencies', 'view_agencies.php', 6, 1),
                            (77, 'Agency Booking Notes', 'agency_booking_notes.php', 6, 1),
                            (78, 'Agency Logins', 'user_manager.php', 6, 0),
                            (79, 'Agency Portal Data', 'agency_portal_data.php', 6, 0),
                            (80, 'Deactivated Agencies', 'view_deactivated_agencies.php', 6, 0),
                            (81, 'Franchise Groups', 'franchise_groups.php', 6, 0),
                            (82, 'Add Calendar Entry', 'add_calendar_entry_static.php', 7, 1),
                            (83, 'My Calendar', 'view_individual_staff_calendar.php', 7, 1),
                            (84, 'Staff Calendar', 'view_tech_calendar.php', 7, 1),
                            (85, 'Add Users', 'add_sats_user.php', 8, 1),
                            (86, 'View Users', 'view_sats_users.php', 8, 0),
                            (87, 'ADD Prospects', 'add_prospects.php', 9, 1),
                            (88, 'Sales Activity', 'sales_activity.php', 9, 0),
                            (89, 'Sales Documents', 'sales_documents.php', 9, 1),
                            (90, 'Sales Emails', 'send_email_template.php', 9, 1),
                            (91, 'Sales Snapshot', 'sales_snapshot.php', 9, 0),
                            (92, 'Target Agencies', 'view_target_agencies.php', 6, 1),
                            (93, 'View All Agencies', 'view_all_agencies.php', 9, 1),
                            (94, 'Expense Form', 'expense.php', 10, 1),
                            (95, 'Incident Form', 'incident_and_injury_report.php', 10, 1),
                            (96, 'Incident Summary', 'incident_and_injury_report_list.php', 10, 0),
                            (97, 'Leave Request Form', 'leave_form.php', 10, 1),
                            (98, 'Leave Summary', 'leave_requests.php', 10, 0),
                            (99, 'Accommodation', 'accomodation.php', 11, 1),
                            (100, 'Add Alarm', 'add_alarm.php', 11, 1),
                            (101, 'Agency Banners', 'banners.php', 11, 0),
                            (102, 'Agency Noticeboard', 'noticeboard.php', 11, 1),
                            (103, 'Agency Portal Special Agencies', 'agency_portal_special_agencies.php', 11, 0),
                            (104, 'Agent Site Documents', 'resources.php', 6, 1),
                            (105, 'Alarm Guide', 'alarm_guide.php', 11, 1),
                            (106, 'Alarm Pricing Page', 'alarm_pricing_page.php', 11, 1),
                            (107, 'Booking Regions', 'view_regions.php', 11, 1),
                            (108, 'Countries', 'countries.php', 11, 1),
                            (109, 'Renewals Created', 'create_renewals.php', 11, 1),
                            (110, 'Create Support Ticket', 'crm_tasks.php', 11, 0),
                            (111, 'Email Templates', 'email_templates.php', 11, 0),
                            (112, 'Email Templates', 'email_templates.php', 11, 1),
                            (113, 'Internal Documents', 'admin_doc.php', 11, 1),
                            (114, 'Maintenance Mode', 'agency_site_maintenance_mode.php', 11, 1),
                            (115, 'Passwords', 'passwords.php', 11, 1),
                            (116, 'Search Emails', 'search_emails.php', 11, 1),
                            (117, 'Suppliers', 'suppliers.php', 11, 0),
                            (118, 'Create Messages', 'create_message.php', 12, 1),
                            (119, 'Incoming', 'incoming_sms.php', 15, 1),
                            (120, 'Job Feedback', 'job_feedback.php', 15, 1),
                            (121, 'Outgoing', 'outgoing_sms.php', 15, 1),
                            (122, 'Send SMS', 'sms.php', 12, 0),
                            (123, 'SMS Templates', 'sms_messages.php', 12, 0),
                            (124, 'View Messages', 'messages.php', 12, 1),
                            (125, 'Add Tools', 'add_tools.php', 13, 1),
                            (126, 'Add Vehicle', 'add_vehicle.php', 13, 1),
                            (127, 'KMS Report', 'kms.php', 13, 0),
                            (128, 'View Tools', 'view_tools.php', 13, 0),
                            (129, 'View Vehicles', 'view_vehicles.php', 13, 0),
                            (130, 'Adjustment Request', 'create_credit_request.php', 14, 0),
                            (131, 'Adjustment Request Summary', 'credit_requests.php', 14, 0),
                            (132, 'Debtors Report', 'debtors_report.php', 14, 0),
                            (133, 'Expense Claims Summary', 'expense_summary.php', 14, 0),
                            (134, 'NLM Properties', 'nlm_properties.php', 14, 0),
                            (135, 'Printer Tracker', 'printing_tracker.php', 14, 0),
                            (136, 'Receipting', 'remittance.php', 14, 1),
                            (137, 'Statements', 'statements.php', 14, 1),
                            (138, 'To Be Printed', 'to_be_printed.php', 14, 0),
                            (139, 'Menu Manager', 'menu_manager.php', 11, 1),
                            (140, 'Reports', 'reports.php', 4, 1),
                            (141, 'Payments & Credits', 'payments_credits.php', 14, 0),
                            (142, 'Send Statements', 'send_statements.php', 14, 1),
                            (143, 'Add Warranty', 'add_warranties.php', 5, 1),
                            (144, 'Warranty Report', 'warranty_report.php', 5, 1),
                            (145, 'Agency Audits', 'agency_audits.php', 9, 1),
                            (146, 'Short Term Rentals', 'holiday_rentals.php', 3, 1),
                            (147, 'Office to Call', 'bne_to_call.php', 2, 1),
                            (148, 'NLM Properties', 'nlm_properties.php', 14, 1),
                            (149, 'Target Agencies', 'view_target_agencies.php', 9, 1),
                            (150, 'View Users', 'view_sats_users.php', 8, 1),
                            (151, 'Sales Snapshot', 'sales_snapshot.php', 9, 1),
                            (152, 'Overdue 60+', 'ageing_jobs_60_to_90.php', 17, 1),
                            (153, 'Overdue 90+', 'ageing_jobs_90.php', 17, 1),
                            (154, 'STR-less Jobs', 'str_less_jobs.php', 2, 1),
                            (155, 'Accounts Logs', 'accounts_logs.php', 14, 1),
                            (156, 'Find 240s', 'find_expired_240v_alarm.php', 2, 0),
                            (157, 'Discarded Alarms', 'discarded_alarms.php', 4, 1),
                            (159, 'Cancelled Jobs', 'cancelled_jobs.php', 3, 0),
                            (160, 'Templates', 'sms/templates', 15, 1),
                            (161, 'Active Unsold Services', 'daily/active_unsold_services', 3, 1),
                            (162, 'Agency Services', 'agency/services', 6, 1),
                            (163, 'No Job Status', 'daily/no_job_status', 3, 1),
                            (164, 'No Job Type', 'daily/no_job_types', 3, 1),
                            (165, 'Multi Agency Portal', 'agency/multi_agency_users', 6, 1),
                            (166, 'Invoiced Jobs', 'jobs/invoiced_jobs', 14, 0),
                            (167, 'Invalid Address', 'reports/dirty_address/', 3, 1),
                            (168, 'API Properties Needs Verification ', 'property_me/properties_needs_verification', 18, 1),
                            (169, 'Agency Payments', 'accounts/agency_payments', 14, 1),
                            (170, 'Cron Jobs', 'cronjobs/index', 11, 1),
                            (171, 'Credit Request2', '/credit/credit_request_summary', 14, 0),
                            (172, 'Credit Request', 'credit/credit_request_summary', 14, 1),
                            (173, 'Refund Request', 'credit/refund_request_summary', 14, 1),
                            (174, 'Upgrade Data Discrepancy', 'daily/incorrectly_upgraded_properties', 17, 1),
                            (175, 'Urgent NSW Jobs', 'daily/view_nsw_act_job_with_tbb', 17, 1),
                            (176, 'Next Service', 'properties/next_service', 17, 1),
                            (177, 'New Jobs', 'send_letter_jobs.php', 2, 0),
                            (178, 'Duplicate Visit', 'daily/duplicate_visit', 3, 1),
                            (179, 'Overdue NSW Jobs', 'daily/overdue_nsw_jobs', 3, 0),
                            (180, 'No Retest Date', 'reports/no_retest_date_property', 3, 1),
                            (181, 'Emergency Action', 'admin/emergency_action', 11, 1),
                            (182, 'Page Totals', 'admin/page_totals', 11, 1),
                            (183, 'Overdue Other Jobs', '/daily/overdue_other_jobs', 2, 0),
                            (184, 'Preferred Time', 'jobs/preferred_time', 17, 1),
                            (185, 'Benchmark Results', 'benchmark/index', 11, 0),
                            (186, 'Benchmark Results', 'benchmark/index', 11, 1),
                            (187, 'API Inactive Properties', 'properties/inactive_properties_on_api', 18, 1),
                            (188, 'Create Credit Request', 'credit/credit_request', 14, 1),
                            (189, 'Create Refund Request', 'credit/refund_request', 14, 1),
                            (190, 'Active Properties Without Jobs', 'daily/active_properties_without_jobs', 3, 1),
                            (191, 'Linked Properties', 'agency_api/linked_properties', 18, 1),
                            (192, 'Palace Agents', 'palace/agent_palace', 18, 1),
                            (193, 'Palace Bulk Match', 'palace/index', 18, 1),
                            (194, 'Palace Diary Code', 'palace/diary_palace', 18, 1),
                            (195, 'Palace Suppliers', 'palace/supplier_palace', 18, 1),
                            (196, 'PropertyMe Agent Connections', 'property_me/agency_connections', 18, 1),
                            (197, 'PropertyMe Bulk Match', 'property_me/bulk_connect', 18, 1),
                            (198, 'PropertyMe Suppliers (Billing Connection)', 'property_me/supplier_pme', 18, 1),
                            (199, 'Booking Schedule', 'booking_schedule.php', 17, 1),
                            (200, 'Overdue Jobs', 'daily/overdue_jobs', 17, 0),
                            (201, 'Service Overview', 'gmapproperties', 11, 1),
                            (202, 'Properties with Coordinate Errors', 'reports/properties_with_coordinates_errors', 3, 1),
                            (203, 'Tech Regions', '/tech_regions/index', 11, 1),
                            (204, 'OurTradie Bulk Match', 'ourtradie/bulk_connect', 18, 1),
                            (205, 'Add Sales Properties', '/properties/add_sales_properties', 1, 1),
                            (206, 'Send SMS', '/sms/send', 15, 1),
                            (207, 'Properties With Multiple Service', '/properties/properties_with_multiple_services', 3, 1),
                            (208, 'Missed Jobs', '/jobs/missed_jobs', 17, 1),
                            (209, 'View All Agencies', 'agency/view_all_agencies', 6, 1),
                            (210, 'Console Bulk Match', 'console/bulk_connect', 18, 1),
                            (211, 'Console Unprocessed Webhooks', 'console/unprocessed_webhooks', 18, 1),
                            (212, 'View Vehicles', '/vehicles/view_vehicles', 13, 1),
                            (213, 'Property Tree Bulk Match', 'property_tree/bulk_connect', 18, 1),
                            (214, 'Property Tree Connect Agency', 'property_tree/connect_agency', 18, 1),
                            (215, 'Support Tickets', '/reports/view_crm_tasks/', 20, 1),
                            (216, 'API Un-Linked Properties', '/reports/api_unlinked_properties', 18, 1),
                            (217, 'Feedback Tickets', '/reports/view_complaints', 21, 1),
                            (218, 'Console Tenants Info', 'console/tenants_info', 18, 0),
                            (219, 'Console Compliance Info', 'console/compliance_info', 18, 0),
                            (220, 'PropertyMe Updated Tenants', 'property_me/updated_tenants', 18, 1),
                            (221, 'Workorders and Unlinked SMS', '/sms/workorders_and_unlinked_sms', 15, 1),
                            (222, 'Change of Address Form', '/users/change_address', 10, 1)";

        return $this->query($sql);
    }

    private function crm_page_permission_user(){

    }

    private function crm_page_permission_class(){

    }
}
